font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

draw_minimal_borders no
background_opacity 0.8
dynamic_background_opacity yes

window_padding_width 10

scrollback_lines 1000
wheel_scroll_multiplier 3.0

clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask

url_style        curly
open_url_with    default
detect_urls      yes
url_regex        (ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+

confirm_os_window_close 0

disable_ligatures never
adjust_line_height 1

remember_window_size = yes
initial_window_width 800
initial_window_height 400

foreground #D8DEE9

color0  #2E3440
color8  #4C566A

color1  #BF616A
color9  #D57780

color2  #A3BE8C
color10 #B5D19A

color3  #EBCB8B
color11 #F2D399

color4  #81A1C1
color12 #8FAFD2

color5  #B48EAD
color13 #C6A0C1

color6  #88C0D0
color14 #9AD1E0

color7  #D8DEE9
color15 #ECEFF4
