font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0
cursor_shape beam
cursor_trail 1

draw_minimal_borders no
background_opacity 0.8
dynamic_background_opacity yes

window_padding_width 10

scrollback_lines 1000
wheel_scroll_multiplier 3.0

clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask

url_style        curly
open_url_with    default
detect_urls      yes
url_regex        (ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+

confirm_os_window_close 0

disable_ligatures never
adjust_line_height 1

remember_window_size = yes
initial_window_width 800
initial_window_height 400

foreground #D8DEE9

# Base
background #1a1822
foreground #c9c1d9

# Black
color0  #1a1822
color8  #7b6974

# Red (теплый)
color1  #ad8658
color9  #c99a6a

# Green (приглушенный)
color2  #8477a9
color10 #9a8cc2

# Yellow (акцент)
color3  #f9e559
color11 #fff07a

# Blue (фиолетовый сдвиг)
color4  #73659b
color12 #8b7db5

# Magenta
color5  #8477a9
color13 #b0a3d6

# Cyan (смесь фиол+серого)
color6  #7b6974
color14 #9a8793

# White
color7  #c9c1d9
color15 #f0eaff

include ~/.cache/wal/colors-kitty.conf
